# Generated by Django 6.0.3 on 2026-03-14 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Günlük'), ('weekly', 'Haftalık'), ('monthly', 'Aylık'), ('yearly', 'Yıllık')], default='daily', max_length=10, verbose_name='Periyot')),
                ('rank', models.PositiveSmallIntegerField(help_text='1 ile 10 arasında olmalıdır', verbose_name='Sıralama')),
                ('score', models.FloatField(default=0.0, help_text='view_count + (like_count * 3) formülü ile hesaplanır', verbose_name='Hesaplanan Skor')),
                ('is_manual', models.BooleanField(default=False, help_text='Admin tarafından manuel seçildiyse True', verbose_name='Manuel Seçim')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='poems.poem', verbose_name='Şiir')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlights_selected', to=settings.AUTH_USER_MODEL, verbose_name='Seçen Admin')),
            ],
            options={
                'verbose_name': 'Öne Çıkan',
                'verbose_name_plural': 'Öne Çıkanlar',
                'db_table': 'highlights',
                'ordering': ['period', 'rank'],
                'unique_together': {('period', 'rank')},
            },
        ),
    ]
