# Generated by Django 6.0.3 on 2026-03-30 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverification_alter_poetprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='username',
        ),
    ]
