# Generated by Django 6.0.3 on 2026-03-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_emailverification_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='iuser_wuser_zuser_uuser_zuser_cuser_ouser_j', error_messages={'unique': 'This username is already taken.'}, max_length=150, unique=True),
        ),
    ]
