# Generated by Django 6.0.3 on 2026-03-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Ulanyjy', 'verbose_name_plural': 'Ulanyjylar'},
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=['9', '6', '2', '7', '1', '8', '2', '3', '0', '7', '3', '1', '1', '0'], error_messages={'unique': 'This username is already taken.'}, max_length=150, unique=True),
        ),
    ]
