# Generated by Django 6.0.3 on 2026-03-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_options_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='92794720001494', error_messages={'unique': 'This username is already taken.'}, max_length=150, unique=True),
        ),
    ]
