# Generated by Django 6.0.3 on 2026-04-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_username_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='60814695959151', error_messages={'unique': 'This username is already taken.'}, max_length=150, unique=True),
        ),
    ]
