# Generated by Django 6.0.3 on 2026-04-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='99946508970811', error_messages={'unique': 'This username is already taken.'}, max_length=150, unique=True),
        ),
    ]
