# Generated by Django 6.0.3 on 2026-04-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_poetprofile_social_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='07411485509950', error_messages={'unique': 'This username is already taken.'}, max_length=150, unique=True),
        ),
    ]
