# Generated by Django 6.0.3 on 2026-04-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poetprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='/poet_images/default.webp', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='57782200479660', error_messages={'unique': 'This username is already taken.'}, max_length=150, unique=True),
        ),
    ]
