# Generated by Django 6.0.3 on 2026-03-14 09:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Başlık')),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(20)], verbose_name='İçerik')),
                ('tags', models.CharField(blank=True, default='', help_text='Virgülle ayrılmış etiketler: aşk, doğa, hüzün', max_length=500, verbose_name='Etiketler')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='poems/backgrounds/', verbose_name='Arka Plan Görseli')),
                ('background_music', models.CharField(choices=[('none', 'None'), ('rain', 'Rain'), ('forest', 'Forest'), ('ocean', 'Ocean'), ('wind', 'Wind'), ('fire', 'Fire'), ('night', 'Night'), ('piano', 'Piano'), ('guitar', 'Guitar'), ('violin', 'Violin')], default='none', max_length=20, verbose_name='Arka Plan Müzik')),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_draft', models.BooleanField(default=False, verbose_name='Taslak')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silindi')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poems', to='categories.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Şiir',
                'verbose_name_plural': 'Şiirler',
                'db_table': 'poems',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PoemView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='poems.poem', verbose_name='Şiir')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poem_views', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Görüntülenme',
                'verbose_name_plural': 'Görüntülenmeler',
                'db_table': 'poem_views',
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('poem', 'user'), name='unique_poem_user_view'), models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('poem', 'ip_address'), name='unique_poem_ip_view')],
            },
        ),
    ]
