# Generated by Django 6.0.3 on 2026-04-04 12:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('poems', '0003_poem_approve'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Goşgy', 'verbose_name_plural': 'Goşgular'},
        ),
        migrations.AlterModelOptions(
            name='poemview',
            options={'verbose_name': 'Okalma sany', 'verbose_name_plural': 'Okalanlar sany'},
        ),
        migrations.AlterField(
            model_name='poem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to=settings.AUTH_USER_MODEL, verbose_name='Ýazyjy'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='background_image',
            field=models.CharField(choices=[('none', 'None'), ('night', 'Night'), ('snow', 'Snow'), ('forest', 'Forest'), ('ocean', 'Ocean'), ('candle', 'Candle'), ('rain', 'Rain'), ('books', 'Books'), ('hope', 'Hope'), ('dark', 'Dark')], default='none', max_length=50, verbose_name='Arka fon suraty'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='background_music',
            field=models.CharField(choices=[('none', 'None'), ('rain', 'Rain'), ('forest', 'Forest'), ('ocean', 'Ocean'), ('wind', 'Wind'), ('fire', 'Fire'), ('night', 'Night'), ('piano', 'Piano'), ('guitar', 'Guitar'), ('violin', 'Violin')], default='none', max_length=20, verbose_name='Arka fon sazy'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poems', to='categories.category', verbose_name='Kategoriýa'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='comment_permission',
            field=models.BooleanField(default=True, verbose_name='Teswir rugsady'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Goşgy'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Pozuldy'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Garalama'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='poem_note',
            field=models.TextField(blank=True, default='', verbose_name='Şahyryň belligi'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='public_status',
            field=models.CharField(choices=[('public', 'Public'), ('followers', 'Followers'), ('private', 'Private')], default='public', max_length=20, verbose_name='Kimler görmeli'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Oty belgisi bilen taglary girizip bolýar: söýgi, tebigat, ýalňyzlyk', max_length=500, verbose_name='Taglar'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='poemview',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='poems.poem', verbose_name='Goşgy'),
        ),
        migrations.AlterField(
            model_name='poemview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poem_views', to=settings.AUTH_USER_MODEL, verbose_name='Ulanyjy'),
        ),
    ]
